// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqanfbnojuvszhitodyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxYW5mYm5vanV2c3poaXRvZHl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NDY0NjgsImV4cCI6MjA3MDIyMjQ2OH0.gXnL4LTvQuaHJgCnGZ9IZmxhMiM3nRcpDPX9xzlCIZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});